# https://taskfile.dev

version: '3'

env:
  ENV: dev

dotenv: ['.env', '.env.{{.ENV}}']

vars:
  GREETING: Hello, World!

tasks:
  startUp:
    cmds:
      - chmod +x ./bootstrap.sh
      - ./bootstrap.sh


  composeUp:
    cmds:
      - docker-compose --env-file ./.env.dev up

  gatewayUp:
    cmds:
      - docker-compose -f gateway-compose.yml up

  composeDown:
    cmds:
      - docker-compose --env-file ./.env.dev down --remove-orphans

  dockerVolume:
    cmds:
      - echo "Removing Docker volumes"
      - docker volume rm $(docker volume ls -q)

  dockerBuildBackend:
    cmds: 
      - docker build -f ./apps/backend/Dockerfile --build-arg SCOPE="backend" --build-arg SCOPE="backend" --build-arg PORT=6000 --tag youtube-clone/backend .

  goInsideContainer:
    cmds:
      - docker run --rm -it --entrypoint /bin/sh youtube-clone/backend:latest

  rtsp:
    cmds:
      - docker run --rm -it -e RTSP_PROTOCOLS=tcp -p 8554:8554 -p 1935:1935 -p 8888:8888 aler9/rtsp-simple-server