---
apiVersion: v1
# Kind for kubernets ConfigMap
kind: ConfigMap
metadata:
    # Name your ConfigMap
    name: postgres-config
    labels:
        app: postgres
data:
    postgres-host: postgres-service:5432
    POSTGRES_DB: postgresdb
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: password123
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: postgres-initdb-config
data:
    initdb.sql: |
        CREATE USER my_app WITH PASSWORD 'password123';
        CREATE DATABASE my_app_db;
        GRANT ALL PRIVILEGES ON DATABASE my_app_db TO my_app;

        CREATE USER hasura WITH PASSWORD 'password123';
        CREATE DATABASE hasura_metadata;
        GRANT ALL PRIVILEGES ON DATABASE hasura_metadata TO hasura;

        CREATE USER fusionauth WITH PASSWORD 'password123';
        CREATE DATABASE fusionauth_db;
        GRANT ALL PRIVILEGES ON DATABASE fusionauth_db TO fusionauth;

        ALTER DEFAULT PRIVILEGES FOR ROLE my_app GRANT ALL PRIVILEGES ON TABLES TO hasura;
        ALTER DEFAULT PRIVILEGES FOR ROLE hasura GRANT ALL PRIVILEGES ON TABLES TO my_app;
---
kind: PersistentVolume
apiVersion: v1
metadata:
    name: postgres-pv-volume # Sets PV's name
    labels:
        type: local # Sets PV's type to local
        app: postgres
spec:
    storageClassName: local-path
    capacity:
        storage: 600Mi # Sets PV Volume
    accessModes:
        - ReadWriteMany
    hostPath:
        path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: postgres-pv-claim # Sets name of PVC
    labels:
        app: postgres
spec:
    storageClassName: local-path
    accessModes:
        - ReadWriteMany # Sets read and write access
    resources:
        requests:
            storage: 400Mi # Sets volume size
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres # Sets Deployment name
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            containers:
                - name: postgres
                  image: ghcr.io/mrtousif/postgres-15:a8692e4263a81aaf67e6b3e07be1d64ec4ba839d # Sets Image
                  imagePullPolicy: "IfNotPresent"
                  ports:
                      - containerPort: 5432 # Exposes container port
                  envFrom:
                      - configMapRef:
                            name: postgres-config
                  volumeMounts:
                      - mountPath: /var/lib/postgresql/data
                        name: postgredb
                      - name: postgres-initdb
                        mountPath: /docker-entrypoint-initdb.d
            volumes:
                - name: postgredb
                  persistentVolumeClaim:
                      claimName: postgres-pv-claim
                - name: postgres-initdb
                  configMap:
                      name: postgres-initdb-config

---
apiVersion: v1
kind: Service
metadata:
    name: postgres-service # Sets service name
    labels:
        app: postgres # Labels and Selectors
spec:
    type: NodePort # Sets service type
    ports:
        - port: 5432 # Sets port to run the postgres application
          nodePort: 30000
    selector:
        app: postgres
