---
kind: PersistentVolume
apiVersion: v1
metadata:
    name: postgres-pv-volume # Sets PV's name
    labels:
        type: local # Sets PV's type to local
        app: postgres
spec:
    storageClassName: manual
    capacity:
        storage: 600Mi # Sets PV Volume
    accessModes:
        - ReadWriteMany
    hostPath:
        path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: postgres-pv-claim # Sets name of PVC
    labels:
        app: postgres
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteMany # Sets read and write access
    resources:
        requests:
            storage: 400Mi # Sets volume size
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres # Sets Deployment name
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            containers:
                - name: postgres
                  image: postgres:15-alpine # Sets Image
                  imagePullPolicy: "IfNotPresent"
                  ports:
                      - containerPort: 5432 # Exposes container port
                  envFrom:
                      - configMapRef:
                            name: postgres-config
                  volumeMounts:
                      - mountPath: /var/lib/postgresql/data
                        name: postgredb
                      - name: postgres-initdb
                        mountPath: /docker-entrypoint-initdb.d
            volumes:
                - name: postgredb
                  persistentVolumeClaim:
                      claimName: postgres-pv-claim
                - name: postgres-initdb
                  configMap:
                      name: postgres-initdb-config

---
apiVersion: v1
kind: Service
metadata:
    name: postgres-service # Sets service name
    labels:
        app: postgres # Labels and Selectors
spec:
    type: NodePort # Sets service type
    ports:
        - port: 5432 # Sets port to run the postgres application
    selector:
        app: postgres
