name: Backport merged pull request
on:
  pull_request:
    types: [closed]
permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests
  
jobs:
  backport:
    name: Backport pull request
    runs-on: ubuntu-latest
    # Don't run on closed unmerged pull requests
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v3
      - name: Create backport pull requests
        uses: korthout/backport-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # Optional
          # Working directory for the backport action
          # github_workspace: ${{ github.workspace }}

          # Optional
          # Regex pattern to match github labels
          # Must contain a capture group for the target branch
          # label_pattern: ^backport ([^ ]+)$

          # Optional
          # Template used as description in the pull requests created by this action.
          # Placeholders can be used to define variable values.
          # These are indicated by a dollar sign and curly braces (`${placeholder}`).
          # Please refer to this action's README for all available placeholders.
          # pull_description: |-
          #   # Description
          #   Backport of #${pull_number} to `${target_branch}`.

          # Optional
          # Template used as the title in the pull requests created by this action.
          # Placeholders can be used to define variable values.
          # These are indicated by a dollar sign and curly braces (`${placeholder}`).
          # Please refer to this action's README for all available placeholders.
          # pull_title: "[Backport ${target_branch}] ${pull_title}"

          # Optional
          # Regex pattern to match github labels which will be copied from the
          # original pull request to the backport pull request. By default, no
          # labels are copied.
          # copy_labels_pattern: ''