name: CI

on:
    pull_request:

jobs:
    ci:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 2

            - name: Install Task
              uses: arduino/setup-task@v1

            - uses: pnpm/action-setup@v2.2.4
              with:
                  version: 7

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Extract out parent branch
              shell: bash
              run: echo "##[set-output name=parent_branch;]$(git show-branch -a | grep '\*' | grep -v `git rev-parse --abbrev-ref HEAD` | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//')"
              id: extract_parent_branch

            - name: Install dependencies
              run: pnpm install

            - name: Lint, test and build (pull request)
              if: ${{ github.event_name == 'pull_request' }}
              run: pnpm turbo run build --filter=[HEAD^1]

            - name: Get if there is jest report file
              id: changed-jest-report
              uses: tj-actions/changed-files@v35
              with:
                files: '**/jest-*.xml'

            - name: Test Report
              uses: dorny/test-reporter@v1
              if: steps.changed-jest-report.outputs.any_changed == 'true'
              with:
                name: JEST Tests            
                path: '**/reports/jest-*.xml'    
                reporter: jest-junit        

            - name: Danger
              run: pnpm danger ci
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - uses: EndBug/add-and-commit@v9
              with:
                default_author: github_actor

            - name: Detect Secrets
              uses: trufflesecurity/trufflehog@v3.6.7
              with:
                path: ./
                base: ${{ github.event.repository.default_branch }}
                head: HEAD

            # - name: Get changed files in the docs folder
            #   id: changed-hasura-metadata
            #   uses: tj-actions/changed-files@v35
            #   with:
            #     files: apps/hasura/metadata/**.yaml

            # - name: Detect Hasura metadata changes
            #   uses: Fieldguide/action-hasura-change-summary@v2
            #   if: steps.changed-hasura-metadata.outputs.any_changed == 'true'
            #   id: hasura-change-summary
            #   with:
            #     hasura_endpoint: https://my-pr-${{ github.event.number }}-app.example.com

            # - name: Create or update summary comment
            #   uses: marocchino/sticky-pull-request-comment@v2
            #   if: steps.hasura-change-summary.outputs.change_html
            #   with:
            #     header: hasura-change-summary
            #     message: ${{ steps.hasura-change-summary.outputs.change_html }}
